### PR TITLE
Player Names with Special Characters

### PR DESCRIPTION
**Pull request by Rossiar**
It'd be great if you could create a release after this update - then I can delete our fork and use your module as is - right now because you don't have a release I have to use the following in my `go.mod`:

```
require (
	github.com/janstuemmel/csgo-log v1.0.0
)

replace github.com/janstuemmel/csgo-log => github.com/faceit/csgo-log v1.1.1
```

### CODE REVIEW

**Comment by janstuemmel** [comment]
ok i will review and bump to 2.0.1 then

**Comment by janstuemmel** [comment]
`.travis.yml` should be updated to go version 1.3 as well

**Comment by Rossiar** [comment]
I updated it and force-pushed, the build passed so lgtm

**Comment by janstuemmel** [comment]
merged and tagged to version `v2.0.1`. Tanks for all the work!

**Pull request merged**
